label: Team Member
context:
  name: '@headline.text'
  text:
    processed: '@text.formatted'
  portrait:
    alt: A placeholder
    image:
      url: 'https://via.placeholder.com/800x1200'
      width: 800
      height: 1200
  articles: { teasers: '@teaser-box.teasers' }
  jobs: { teasers: '@teaser-box.teasers' }
