fragment TeamMember on NodeTeamMember {
  name:entityLabel
  text:body {
    processed
  }

  portrait:fieldImage {
    alt
    image:derivative(style: PORTRAIT) {
      url
      width
      height
    }
  }

  articles:relatedArticles {
    teasers:results {
      ... Teaser
    }
  }

  jobs:relatedJobs {
    teasers:results {
      ... Teaser
    }
  }
}
