language: php
dist: trusty
sudo: false

php:
  - 7.2
node_js:
  - 10.9

cache:
  directories:
  - ~/.npm
  - ~/.cache
  - ~/.composer/cache

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer self-update

install:
  - composer install
  - cd tests && npm install && cd ..
  - source .envrc

script:
  - silverback setup
  - if [[ -n "$SB_JIRA_PROJECTS" ]]; then silverback download-tests; fi
  - drush serve > log.txt 2>&1 &
  - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; sleep 1; curl -I http://127.0.0.1:8888 ; do true; done
  - if [[ -d web/modules/custom ]]; then phpunit web/modules/custom; fi
  - |
    cd tests
    # The regex to get jira issue number from a git branch.
    regex='(.*)(^|/)([A-Z]+[A-Z0-9]?-[0-9]+)(.*)'
    # Get git branch.
    branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
    # Get the jira issue number from branch name and add it to cypress tags. Or
    # run only completed tests.
    [[ $branch =~ $regex ]] && \
      export CYPRESS_TAGS="@${BASH_REMATCH[3]} or @COMPLETED" || \
      export CYPRESS_TAGS="@COMPLETED"
    echo "Going to run cypress with the following tags: $CYPRESS_TAGS"
    cypress run
  - kill $(jobs -p) || true

notifications:
  email: false

