label: Headlines
context:
  level: 1
  text: Are you ready for the truth?

variants:
  - name: Level 2
    context:
      level: 2
      text: No man, I don't eat pork.
  - name: Level 3
    context:
      level: 3
      text: We happy?
  - name: Level 4
    context:
      level: 4
      text: Uuummmm, this is a tasty burger!
  - name: Level 5
    context:
      level: 5
      text: I'm serious as a heart attack.
  - name: Level 6
    context:
      level: 6
      text: Hold on to your butts.
