label: Teaser box

context: &default
  title: Some teasers
  theme: white
  teasers: '@teaser-list.teasers'
  url: '#'

variants:
  - name: Black
    context:
      <<: *default
      theme: black
  - name: Yellow
    context:
      <<: *default
      theme: yellow


