label: Teaser list

context:
  teasers:
  - title: '@headline.text'
    date: ''
    url:
      path: '#'
  - title: '@headline.text'
    date: ''
    url:
      path: '#'
    thumbnail:
      alt: A placeholder image
      image:
        url: 'https://via.placeholder.com/100x100'
        width: 100
        height: 100
  - title: '@headline.text'
    date: ''
    url:
      path: '#'
