label: Teaser
context: &default
  title: '@headline.text'
  date: ''
  url:
    path: '#'

variants:
  - name: With thumbnail
    context:
      <<: *default
      thumbnail:
        alt: A placeholder image
        image:
          url: 'https://via.placeholder.com/100x100'
          width: 100
          height: 100

